package com.depaul.cdm.se452.group6.movie.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Entity
@Table(name = "alcohol")
public class AlcoholItem implements Serializable {

    //Id, autogenerated
    @Id
    @GeneratedValue
    private Long id;

    //Alcohol Type, functions as the name of the alcohol
    private String type;

    //Price per type
    private Double price;

}
